mongodb-data:
  image: busybox
  container_name: mongodb-data 
  volumes:
      - /data/db 

mongodb:
  image: mongo
  container_name: mongodb
  hostname: mongodb
  volumes_from:
      - mongodb-data
  restart: always
  ports:
      - "27017:27017"
  net: host
  command: mongod --storageEngine=wiredTiger --wiredTigerCacheSizeGB=1 --notablescan --journalCommitInterval=300 --directoryperdb 

mysql-data:
  image: busybox
  container_name: mysql-data 
  volumes:
      - /var/lib/mysql 
      - /etc/mysql/conf.d 

mysql:
  image: mysql
  container_name: mysql
  hostname: mysql
  volumes_from:
      - mysql-data
  restart: always
  ports:
      - "3306:3306"
  net: host
  environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: sushe

rabbitmq-data:
  image: busybox
  container_name: rabbitmq-data 
  volumes:
      - /var/lib/rabbitmq 

rabbitmq:
  image: rabbitmq:management
  container_name: rabbitmq
  hostname: rabbitmq
  volumes_from:
      - rabbitmq-data
  restart: always
  ports:
      - "5672:5672"
      - "15672:15672"
  net: host
  # limit RabbitMQ to 1GB of RAM or it will steal 40% of available memory
  mem_limit: 1000000000
  environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

redis-data:
  image: busybox
  container_name: redis-data
  volumes:
      - /data

redis:
  image: redis 
  container_name: redis
  hostname: redis
  volumes_from:
      - redis-data
  restart: always
  ports:
      - "6379:6379"
  net: host

